### ISSUE TITLE
Fix parsing issues with new website

### ISSUE THREAD

**Issue by victorjoos** [gabriel-vanzandycke/tgif#8]
https://uclouvain.be/fr/etudier/calendrier-academique.html has changed and we need to parse it correctly

**Comment by victorjoos** [comment]
ça a l'air de marcher sur ma machine... @gabriel-vanzandycke  ?

**Comment by gabriel-vanzandycke** [comment]
j'ai juste débranché la machine :D

**Comment by gabriel-vanzandycke** [comment]
Solved by launching worker again
